### ISSUE TITLE
Generate two different versions of the same image

### ISSUE THREAD

**Issue by arggh** [axe312ger/metalsmith-sharp#19]
Is there an easy way to create two different versions, for example one with the specific target resolution and one with the same resolution doubled, named respectively `image@1x.jpg` and `image@2x.jpg`?

I gave it a quick shot, and I ended up with:

`image@1x.jpg` `image@1x@2x.jpg` and `image@2x.jpg`.

I think this is quite a common use case.

**Comment by arggh** [comment]
Got it done with this [matcher](http://www.globtester.com/#p=eJzT19LS19JQ1NByMKzQ1NRz0MgqSK%2FJKkhNrynIS9cEAG2JCJY%3D&r=eJyzScksU0jOSSwutlXKTSxJzlCy08%2FMTUxPLdZPySwq1i%2FITNbLKki3AfLK7GyQFGOqczCswK4UzVxDoKpUrCbaJBXZQcQBf2Uzaw%3D%3D&): `**/*(!(*@1x)).@(jpg|jpeg|png)` and doing a second pass with Sharp,  but it makes my build process duration jump from couple of seconds to over a minute.

**Comment by arggh** [comment]
Got the speed back by doing a little tweak, final matcher: `**/*(!(*@1x.)+(jpg|jpeg|png))`.

Maybe a similar example matcher should be in the docs? (or then I couldn't figure out the "proper" way to accomplish this)

edit: I guess one could also use the `metalsmith-branch` plugin to achieve this.

**Comment by axe312ger** [comment]
See the tests here, where I create multiple versions of one image:
https://github.com/axe312ger/metalsmith-sharp/blob/master/test/index.test.js#L168

Alternatively, you can tell the plugin NOT to move files in the first step, so you do another image manipulation different naming. But calling the plugin twice might extend the compile time.

By default, the image is moved, thats why you had to use such a complex matcher.

See here: https://github.com/axe312ger/metalsmith-sharp#movefile

**Comment by arggh** [comment]
I had disabled moving, the problem was that I didn't know I can do this:

```
.use(sharp([{
        src: '**/*.@(jpg|png|jpeg)',
        namingPattern: '{dir}/{name}@1x.jpg',
        methods: [{
          name: 'resize',
          args: [768]
        }, {
          name: 'toFormat',
          args: [ 'jpeg' ]
        }],
        moveFile: false
      }, {
        src: '**/*.@(jpg|png|jpeg)',
        namingPattern: '{dir}/{name}@2x.jpg',
        methods: [{
          name: 'resize',
          args: [1536]
        }, {
          name: 'toFormat',
          args: [ 'jpeg' ]
        }],
        moveFile: false
      }]))
```

So, I would add a section to the docs explaining, that to achieve multiple versions of the same files you can give `sharp` an array of objects as parameter, instead of _only_ an object.

**Comment by axe312ger** [comment]
yes, sure, this is a pretty new feature of the plugin, i missed it in the docs

**Comment by axe312ger** [comment]
i added example code to the usage section in the readme :)

**Comment by arggh** [comment]
Nice, that should clear things up!

**Comment by arggh** [comment]
Also, thanks for a great plugin :)
