### ISSUE TITLE
Link to »minimatch features« in Readme is broken 

### ISSUE THREAD

**Issue by jvolker** [axe312ger/metalsmith-sharp#64]
The link to »minimatch features« in [Readme > Options > src](https://github.com/axe312ger/metalsmith-sharp#src) is broken and currently pointing to `https://github.com/axe312ger/metalsmith-sharp/blob/master`.

**Comment by axe312ger** [comment]
Thank you Volker!

It does now point to the features section of minimatch 😄 

(even though it does not give as many infos as I hoped it would 😓)
